import { describe, it, expect, vi } from 'vitest';
import { mmToPixels, calculatePassportLayout, applyCalibration, DEFAULT_CALIBRATION } from './layout';
import { generatePassportSheet } from './image';
describe('physical layout',()=>{
  it('converts millimeters at 300 DPI',()=>{expect(mmToPixels(25.4)).toBe(300);expect(mmToPixels(35)).toBe(413);expect(mmToPixels(45)).toBe(531)});
  it('makes exact 4×6 canvases',()=>{expect(calculatePassportLayout({photo:{width:35,height:45},copies:8}).width).toBe(1200);expect(calculatePassportLayout({photo:{width:35,height:45},copies:8}).height).toBe(1800);expect(calculatePassportLayout({photo:{width:35,height:45},copies:8,orientation:'landscape'})).toMatchObject({width:1800,height:1200})});
  it.each([4,6,8])('places %i copies',copies=>{const layout=calculatePassportLayout({photo:{width:35,height:45},copies});expect(layout.placements).toHaveLength(copies);expect(layout.capacity).toBeGreaterThanOrEqual(8)});
  it('uses rotated 2×4 portrait layout for eight',()=>{const layout=calculatePassportLayout({photo:{width:35,height:45},copies:8,orientation:'portrait'});expect(layout.placements.every(p=>p.rotated)).toBe(true);expect(new Set(layout.placements.map(p=>p.x)).size).toBe(2);expect(new Set(layout.placements.map(p=>p.y)).size).toBe(4)});
  it('keeps all photos inside margins without overlap',()=>{const layout=calculatePassportLayout({photo:{width:35,height:45},copies:8});for(const [i,a] of layout.placements.entries()){expect(a.x).toBeGreaterThanOrEqual(layout.marginPixels);expect(a.y).toBeGreaterThanOrEqual(layout.marginPixels);expect(a.x+a.width).toBeLessThanOrEqual(layout.width-layout.marginPixels);expect(a.y+a.height).toBeLessThanOrEqual(layout.height-layout.marginPixels);for(const b of layout.placements.slice(i+1))expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true)}});
  it('applies calibration and edge margin',()=>{expect(applyCalibration({width:35,height:45},{horizontal:97.2,vertical:100,edge:3}).width).toBeCloseTo(34.02);const layout=calculatePassportLayout({photo:{width:35,height:45},copies:4,calibration:{...DEFAULT_CALIBRATION,edge:5,horizontal:97.2}});expect(layout.photoPixels.width).toBe(mmToPixels(34.02));expect(layout.marginPixels).toBe(mmToPixels(5))});
  it('generates one full-resolution sheet canvas',()=>{const context={clearRect:vi.fn(),save:vi.fn(),restore:vi.fn(),translate:vi.fn(),rotate:vi.fn(),drawImage:vi.fn(),fillRect:vi.fn(),strokeRect:vi.fn()};vi.stubGlobal('document',{createElement:()=>({width:0,height:0,getContext(){return {...context,canvas:this}}})});const layout=calculatePassportLayout({photo:{width:35,height:45},copies:8});const canvas=generatePassportSheet({width:1600,height:2000} as ImageBitmap,{x:0,y:0,zoom:1,rotation:0},layout);expect([canvas.width,canvas.height]).toEqual([1200,1800]);expect(context.drawImage).toHaveBeenCalledTimes(9);vi.unstubAllGlobals()});
});
