'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { calculatePassportLayout, DEFAULT_CALIBRATION, type Calibration, type Orientation } from '@/lib/layout';
import { drawCrop, exportSheet, generateCalibrationTest, generatePassportSheet, saveBlob, type Crop } from '@/lib/image';
type Settings = { width: number; height: number; copies: number; orientation: Orientation; guides: boolean; calibration: Calibration };
const DEFAULTS: Settings = { width: 35, height: 45, copies: 8, orientation: 'auto', guides: false, calibration: DEFAULT_CALIBRATION };
const INITIAL_CROP: Crop = { x: 0, y: 0, zoom: 1, rotation: 0 };
export default function App() {
  const [settings, setSettings] = useState<Settings>(DEFAULTS);
  const [image, setImage] = useState<ImageBitmap | null>(null);
  const [crop, setCrop] = useState<Crop>(INITIAL_CROP);
  const [showGuide, setShowGuide] = useState(true);
  const [showCalibration, setShowCalibration] = useState(false);
  const [sheet, setSheet] = useState<HTMLCanvasElement | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const input = useRef<HTMLInputElement>(null), editor = useRef<HTMLCanvasElement>(null), preview = useRef<HTMLCanvasElement>(null);
  const drag = useRef<{ x: number; y: number; crop: Crop } | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem('evergreen-passport-settings-v1'); if (saved) { const parsed = JSON.parse(saved); setSettings({ ...DEFAULTS, ...parsed, calibration: { ...DEFAULT_CALIBRATION, ...parsed.calibration } }); } } catch {} }, []);
  useEffect(() => { localStorage.setItem('evergreen-passport-settings-v1', JSON.stringify(settings)); }, [settings]);
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}); }, []);
  useEffect(() => () => { image?.close(); }, [image]);
  const update = (patch: Partial<Settings>) => { setSettings(s => ({ ...s, ...patch })); setSheet(null); };
  const layout = useMemo(() => { try { return calculatePassportLayout({ photo: { width: settings.width, height: settings.height }, copies: settings.copies, orientation: settings.orientation, calibration: settings.calibration }); } catch { return null; } }, [settings]);
  const loadFile = async (file?: File) => {
    if (!file) return;
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError('Choose a JPEG, PNG, or WebP image.'); return; }
    setBusy(true); setError('');
    try { const bitmap = await createImageBitmap(file, { imageOrientation: 'from-image' }); setImage(bitmap); setCrop(INITIAL_CROP); setSheet(null); }
    catch { setError('This image could not be opened. Try another file.'); }
    finally { setBusy(false); if (input.current) input.current.value = ''; }
  };
  const editorWidth = 420, editorHeight = Math.round(420 * settings.height / settings.width);
  useEffect(() => { const canvas = editor.current; if (!canvas || !image) return; canvas.width = editorWidth; canvas.height = editorHeight; const ctx = canvas.getContext('2d'); if (ctx) drawCrop(ctx, image, { width: editorWidth, height: editorHeight }, crop); }, [image, crop, editorWidth, editorHeight]);
  useEffect(() => { const canvas = preview.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; if (image && layout) { const generated = generatePassportSheet(image, crop, layout, settings.guides, .35); canvas.width = generated.width; canvas.height = generated.height; ctx.drawImage(generated, 0, 0); } else { canvas.width = 420; canvas.height = 630; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, canvas.width, canvas.height); } }, [image, crop, layout, settings.guides]);
  const onPointerDown = (e: React.PointerEvent<HTMLCanvasElement>) => { if (!image) return; e.currentTarget.setPointerCapture(e.pointerId); drag.current = { x: e.clientX, y: e.clientY, crop }; };
  const onPointerMove = (e: React.PointerEvent<HTMLCanvasElement>) => { if (!drag.current || !image) return; const rect = e.currentTarget.getBoundingClientRect(); const scale = Math.max(editorWidth / image.width, editorHeight / image.height) * drag.current.crop.zoom; const dx = (e.clientX - drag.current.x) * editorWidth / rect.width / scale; const dy = (e.clientY - drag.current.y) * editorHeight / rect.height / scale; setCrop({ ...drag.current.crop, x: drag.current.crop.x + dx, y: drag.current.crop.y + dy }); setSheet(null); };
  const onPointerUp = () => { drag.current = null; };
  const lowResolution = image && layout ? Math.min(image.width / (layout.photoPixels.width * crop.zoom), image.height / (layout.photoPixels.height * crop.zoom)) < 1 : false;
  const generate = () => { if (!image || !layout) return; setSheet(generatePassportSheet(image, crop, layout, settings.guides)); };
  const save = async (format: 'jpeg' | 'png') => { if (!sheet) return; try { saveBlob(await exportSheet(sheet, format), format === 'jpeg' ? 'jpg' : 'png'); } catch { setError('Could not save the sheet. Please try again.'); } };
  const resetCustomer = () => { setImage(null); setSheet(null); setCrop(INITIAL_CROP); setError(''); if (input.current) input.current.value = ''; };
  const saveCalibration = async () => { try { saveBlob(await exportSheet(generateCalibrationTest(settings.calibration), 'png'), 'png'); } catch { setError('Could not create calibration test.'); } };
  return <div className="app"><header className="header"><div className="brand"><span className="brand-mark">E</span><div><strong>Evergreen</strong><span>Passport Print</span></div></div><div className="header-actions"><span className="private-note">Photos stay on this device</span><button className="text-button" onClick={() => setShowCalibration(!showCalibration)}>Settings / Calibration</button></div></header>
    <main className="workspace"><div className="heading"><div><p className="eyebrow">PRINT WORKSPACE</p><h1>Passport photo sheet</h1><p>Crop once. Print the complete 4 × 6 sheet as one image.</p></div><span className="step-pill">{image ? sheet ? 'Ready to save' : 'Photo loaded' : 'Start with a photo'}</span></div>
      {error && <div className="alert error" role="alert">{error}</div>}
      {showCalibration && <section className="calibration panel"><div className="section-heading"><div><h2>Printer calibration</h2><p>Adjust after measuring a printed test sheet.</p></div><button className="text-button" onClick={() => setShowCalibration(false)}>Close</button></div><div className="field-row three"><label>Horizontal scale correction <span>%</span><input type="number" min="90" max="110" step="0.1" value={settings.calibration.horizontal} onChange={e => update({ calibration: { ...settings.calibration, horizontal: Number(e.target.value) } })} /></label><label>Vertical scale correction <span>%</span><input type="number" min="90" max="110" step="0.1" value={settings.calibration.vertical} onChange={e => update({ calibration: { ...settings.calibration, vertical: Number(e.target.value) } })} /></label><label>Edge margin <span>mm</span><input type="number" min="0" max="20" step="0.5" value={settings.calibration.edge} onChange={e => update({ calibration: { ...settings.calibration, edge: Number(e.target.value) } })} /></label></div><p className="help">If 35 mm prints as 36 mm, enter 97.2% horizontal correction. Settings save on this device.</p><button className="button secondary" onClick={saveCalibration}>Save calibration test PNG</button></section>}
      <div className="columns"><div className="left-column"><section className="panel editor-panel"><div className="section-heading"><div><span className="section-number">01</span><h2>Photo</h2></div>{image && <button className="text-button" onClick={() => input.current?.click()}>Change photo</button>}</div><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e => loadFile(e.target.files?.[0])} />
      {!image ? <div className="dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); loadFile(e.dataTransfer.files[0]); }}><div className="photo-icon">▧</div><h3>Ready for a customer photo</h3><p>Use the camera, photo library, or a file.</p><button className="button primary large" onClick={() => input.current?.click()} disabled={busy}>{busy ? 'Opening…' : 'Take / Choose Photo'}</button><small>JPEG, PNG, or WebP · drag and drop on desktop</small></div> : <><div className="editor-wrap"><div className="editor-frame" style={{ aspectRatio: `${settings.width}/${settings.height}` }}><canvas ref={editor} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} aria-label="Drag to reposition photo" />{showGuide && <div className="crop-guide"><div className="center-line"/><div className="head-guide"/><div className="safe-margin"/></div>}</div></div><div className="editor-controls"><label className="zoom-control">Zoom <input type="range" min="1" max="3" step="0.01" value={crop.zoom} onChange={e => { setCrop({ ...crop, zoom: Number(e.target.value) }); setSheet(null); }} /><span>{Math.round(crop.zoom * 100)}%</span></label><div className="button-row"><button className="button secondary" onClick={() => { setCrop({ ...crop, rotation: (crop.rotation + 90) % 360 }); setSheet(null); }}>Rotate 90°</button><button className="button secondary" onClick={() => { setCrop(INITIAL_CROP); setSheet(null); }}>Reset crop</button><button className={`button ${showGuide ? 'selected' : 'secondary'}`} onClick={() => setShowGuide(!showGuide)}>Face guide</button></div></div>{lowResolution && <div className="alert">Low-resolution image — print may appear soft.</div>}</>}
      </section><section className="panel settings-panel"><div className="section-heading"><div><span className="section-number">02</span><h2>Sheet settings</h2></div><span className="subtle">4 × 6 in · 300 DPI</span></div><div className="setting-block"><div className="setting-label">Copies</div><div className="segmented copies">{[4,6,8].map(n => <button key={n} className={settings.copies === n ? 'active' : ''} onClick={() => update({ copies: n })}>{n} Copies</button>)}<button className={![4,6,8].includes(settings.copies) ? 'active' : ''} onClick={() => update({ copies: 9 })}>Custom</button></div>{![4,6,8].includes(settings.copies) && <label className="custom-count">Requested copies <input type="number" min="1" max="100" value={settings.copies} onChange={e => update({ copies: Number(e.target.value) })} /></label>}</div><div className="setting-block"><div className="setting-label">Passport size <span>mm</span></div><div className="field-row"><label>Width<input type="number" min="10" max="100" step="0.1" value={settings.width} onChange={e => update({ width: Number(e.target.value) })} /></label><label>Height<input type="number" min="10" max="100" step="0.1" value={settings.height} onChange={e => update({ height: Number(e.target.value) })} /></label></div></div><div className="setting-block"><div className="setting-label">Paper orientation</div><div className="segmented">{(['auto','portrait','landscape'] as Orientation[]).map(value => <button key={value} className={settings.orientation === value ? 'active' : ''} onClick={() => update({ orientation: value })}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div><label className="checkbox"><input type="checkbox" checked={settings.guides} onChange={e => update({ guides: e.target.checked })} /> Thin cutting guides on sheet</label></section></div>
      <aside className="right-column"><section className="panel preview-panel"><div className="section-heading"><div><span className="section-number">03</span><h2>Print preview</h2></div><span className="subtle">Entire sheet · one image</span></div><div className="preview-ground"><canvas ref={preview} className="sheet-canvas" style={{ aspectRatio: layout ? `${layout.width}/${layout.height}` : '2/3' }} aria-label="Preview of complete passport photo sheet" /></div><div className="preview-details"><span>{layout ? `${layout.width} × ${layout.height} px` : '1200 × 1800 px'}</span><span>{layout ? `${layout.placements.length} on sheet · ${layout.capacity} fit` : '4 × 6 in'}</span></div>{layout && settings.copies > layout.capacity && <div className="alert">Only {layout.capacity} photos fit at this size. The sheet will include {layout.capacity}.</div>}<button className="button primary generate" disabled={!image || !layout} onClick={generate}>Generate 4×6 Sheet</button>{sheet && <div className="export-actions"><button className="button dark" onClick={() => save('jpeg')}>Save JPG</button><button className="button secondary" onClick={() => save('png')}>Save PNG</button><button className="button secondary" onClick={resetCustomer}>New Customer</button></div>}<p className="print-note">For your HP Photosmart: copy the saved JPG to USB, then select <strong>one photo per page</strong> on 4 × 6 paper.</p></section></aside></div></main><footer>Evergreen Passport Print <span>·</span> Private, on-device processing</footer></div>;
}
